###
post  http://localhost:3000/users/addUser HTTP/1.1
content-type: application/json

{
    "email":"said.imi33@gmail.com",
    "nom": "said",
    "prenom":"BRAIMI",
    "fonction":"Directeur",
    "password": "12345678"
}
###
get  http://localhost:3000/users/getUser/14

###
get  http://localhost:3000/users/getUsers

###

post  http://localhost:3000/users/removeUser/14

###
patch  http://localhost:3000/users/editUser/18
content-type: application/json

{
    "email":"saida.imi33@gmail.com",
    "nom": "saida",
    "prenom":"BRxa",
    "fonction":"Directeur",
    "password": "12345678"
}